name: "Check compatibility"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-compatibility:
    name: 'Check compatibility'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [20, 22]
        eslint: [9]

    steps:
      - uses: actions/checkout@v5

      # https://vercel.com/guides/corepack-errors-github-actions
      - name: Use Latest Corepack
        run: |
          npm install -g corepack@latest
          echo "corepack version => $(corepack --version)"
          corepack enable

      - uses: actions/setup-node@v6
        name: Setup node
        with:
          cache: pnpm
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: pnpm install

      - name: Override ESLint
        working-directory: apps/compatibility-check
        run: pnpm install -D eslint@${{ matrix.eslint }}

      - name: Lint project
        working-directory: apps/compatibility-check
        run: pnpm run lint
