name: "Check package compatibility"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check-compatibility:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20, 22]
        eslint: [8, 9]
